import { Box, Button, SimpleGrid, Text, Title } from '@mantine/core'
import type { Metadata } from 'next'
import styles from './page.module.css'
import Link from 'next/link'
import { FilmImage } from '@/components/FilmImage/FilmImage'
import { FilmRating } from '@/components/FilmRating/FilmRating'

export const metadata: Metadata = {
   title: 'ШИФТ CINEMA',
   description: 'Generated by create next app'
}

const Home = () => (
   <Box mt={48}>
      <Title order={2}>Афиша</Title>
      <SimpleGrid spacing={32} mt={16} className={styles.grid}>
         {[1, 2].map((item) => (
            <Box key={item}>
               <FilmImage />
               <Box mt={16}>
                  <Title order={3}>Пёс (12+) </Title>
                  <Text size="sm" c="#637083">
                     Фильм
                  </Text>
                  <FilmRating />
                  <Button
                     size="md"
                     radius={16}
                     p="16px 32px"
                     w="100%"
                     h="auto"
                     mt={16}
                     component={Link}
                     href="/1"
                  >
                     Подробнее
                  </Button>
               </Box>
            </Box>
         ))}
      </SimpleGrid>
   </Box>
)

export default Home
